### ISSUE TITLE
How to add dimensions with - in the value?

### ISSUE THREAD

**Issue by watsonjm** [aws-samples/amazon-cloudwatch-auto-alarms#7] opened 2021-05-04 23:20 UTC
I'm trying to work with the following dimensions pulled via AWS CLI on a working alarm that I created manually for this purpose:

```
user@PC:~# aws cloudwatch describe-alarms --alarm-names "tester"
...
"Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "i-111111111111111"
                },
                {
                    "Name": "NodeName",
                    "Value": "ip-123-45-123-45.us-east-1.compute.internal"
                },
                {
                    "Name": "ClusterName",
                    "Value": "some-cluster-name"
                }
            ],
...
```

I've been working with this in the cw_auto_alarms.py file to rule out any issues with tagging (before I got to dashes likely being the issue) and have it hard coded in there currently like this:
```
       {
            'Key': 'AutoAlarm-ContainerInsights-node_filesystem_utilization-NodeName-ip-123-45-123-45.us-east-1.compute.internal-ClusterName-some-cluster-name-GreaterThanThreshold-1m-Average',
            'Value': alarm_cpu_high_default_threshold
        }
```
I have also tried wrapping the values with " and also \\" to escape the quotes, but no luck. 

The alarm isn't creating, and I have been able to create other alarms without extra dimensions, so I'm assuming this has something to do with the dashes in the values. This is for custom metrics using ContainerInsights if that helps. Any help is appreciated.

**Comment by knizami** [comment] 2021-05-08 12:04
Hello, thanks for submitting this.  You are correct, the separator is hardcoded.  I am working on fixing this to allow you to specify the separator.  It should be available by Monday.  Also, working on supporting DynamoDB as a persistent store so you don't have to edit the code.  DynamoDB input of alarms will be available in a week or two.

**Comment by knizami** [comment] 2021-05-08 13:25
Hello, I've added a feature to enable you to specify the separator character.  In [./src/cw_auto_alarms.py](./src/cw_auto_alarms.py) you can update the property, **alarm_separator** to a different value such as "~" to enable you to use the "-" character in your alarm properties.

**Comment by knizami** [comment] 2021-05-14 21:09
Hello, closing this issue.  Please let me know if you have any questions on implementing a custom alarm separator.  The documentation has also been updated to include this feature.

**Closed by knizami** 2021-05-14 21:09 UTC

**Comment by Erlichooo** [comment] 2022-05-13 18:25
@watsonjm 
Hello, I have seen that you use the auto-alarm lambda for Container Insight. I want know is that work. I did some job with EKS, and also use Container Insight, but I got some issue for this that alarm could not been created. If any reply I will really appreciate it.

**Comment by watsonjm** [comment] 2022-05-13 18:32
> @watsonjm Hello, I have seen that you use the auto-alarm lambda for Container Insight. I want know is that work. I did some job with EKS, and also use Container Insight, but I got some issue for this that alarm could not been created. If any reply I will really appreciate it.

Hi @Erlichooo 
Yes, I was able to create some custom alarms for EKS Container Insights. It's been a while but I can probably still help, what alarm are you trying to create, and what issues are you having?

**Comment by Erlichooo** [comment] 2022-05-14 18:50
> > @watsonjm Hello, I have seen that you use the auto-alarm lambda for Container Insight. I want know is that work. I did some job with EKS, and also use Container Insight, but I got some issue for this that alarm could not been created. If any reply I will really appreciate it.
> 
> Hi @Erlichooo Yes, I was able to create some custom alarms for EKS Container Insights. It's been a while but I can probably still help, what alarm are you trying to create, and what issues are you having?

Tks so much that your reply @Erlichooo 
I have met the problem that when I set Nodename dimension for the Container Insights auto add/reduce alarm when the EKS add/reduce some nodes. The problem is the alarm of auto part could not work. And I show my node tag just like
`AutoAlarm-ContainerInsights-node_memory_utilization-ClusterName-tmp-GreaterThanThreshold-1m-Average`

I saw your tag with specific dimension 'Nodename', but I thought it is not suit for EKS to auto  add/reduce alarm when the node up or down, because the 'Nodename' likes ec2 dimension 'InstanceId'.

Again, I really thank for your reply, and if you can have any help for me, may be I can share my screen to show my environment with skype\zoom\teams any convenient for you.

**Comment by Erlichooo** [comment] 2022-05-14 18:51
> Tks so much that your reply @Erlichooo I have met the problem that when I set Nodename dimension for the Container Insights auto add/reduce alarm when the EKS add/reduce some nodes. The problem is the alarm of auto part could not work. And I show my node tag just like `AutoAlarm-ContainerInsights-node_memory_utilization-ClusterName-tmp-GreaterThanThreshold-1m-Average`
> 
> I saw your tag with specific dimension 'Nodename', but I thought it is not suit for EKS to auto add/reduce alarm when the node up or down, because the 'Nodename' likes ec2 dimension 'InstanceId'.
> 
> Again, I really thank for your reply, and if you can have any help for me, may be I can share my screen to show my environment with skype\zoom\teams any convenient for you.

Tks so much that your reply @watsonjm 
I have met the problem that when I set Nodename dimension for the Container Insights auto add/reduce alarm when the EKS add/reduce some nodes. The problem is the alarm of auto part could not work. And I show my node tag just like
AutoAlarm-ContainerInsights-node_memory_utilization-ClusterName-tmp-GreaterThanThreshold-1m-Average

I saw your tag with specific dimension 'Nodename', but I thought it is not suit for EKS to auto add/reduce alarm when the node up or down, because the 'Nodename' likes ec2 dimension 'InstanceId'.

Again, I really thank for your reply, and if you can have any help for me, may be I can share my screen to show my environment with skype\zoom\teams any convenient for you.

**Comment by Erlichooo** [comment] 2022-05-15 10:50
> Tks so much that your reply @watsonjm I have met the problem that when I set Nodename dimension for the Container Insights auto add/reduce alarm when the EKS add/reduce some nodes. The problem is the alarm of auto part could not work. And I show my node tag just like AutoAlarm-ContainerInsights-node_memory_utilization-ClusterName-tmp-GreaterThanThreshold-1m-Average
> 
> I saw your tag with specific dimension 'Nodename', but I thought it is not suit for EKS to auto add/reduce alarm when the node up or down, because the 'Nodename' likes ec2 dimension 'InstanceId'.
> 
> Again, I really thank for your reply, and if you can have any help for me, may be I can share my screen to show my environment with skype\zoom\teams any convenient for you.

Tks so much that your reply @watsonjm 
I have met the problem that when I set Nodename dimension for the Container Insights auto add/reduce alarm when the EKS add/reduce some nodes. The problem is the alarm of auto part could not work. And I show my node tag just like
AutoAlarm-ContainerInsights-node_memory_utilization-ClusterName-tmp-GreaterThanThreshold-1m-Average

I saw your tag with specific dimension 'Nodename', but I thought it is not suit for EKS to auto add/reduce alarm when the node up or down, because the 'Nodename' likes ec2 dimension 'InstanceId'.

Again, I really thank for your reply, and if you can have any help for me, may be I can share my screen to show my environment with skype\zoom\teams any convenient for you.

**Comment by Erlichooo** [comment] 2022-05-15 10:51
> > @watsonjm Hello, I have seen that you use the auto-alarm lambda for Container Insight. I want know is that work. I did some job with EKS, and also use Container Insight, but I got some issue for this that alarm could not been created. If any reply I will really appreciate it.
> 
> Hi @Erlichooo Yes, I was able to create some custom alarms for EKS Container Insights. It's been a while but I can probably still help, what alarm are you trying to create, and what issues are you having?

Tks so much that your reply @watsonjm
I have met the problem that when I set Nodename dimension for the Container Insights auto add/reduce alarm when the EKS add/reduce some nodes. The problem is the alarm of auto part could not work. And I show my node tag just like
AutoAlarm-ContainerInsights-node_memory_utilization-ClusterName-tmp-GreaterThanThreshold-1m-Average

I saw your tag with specific dimension 'Nodename', but I thought it is not suit for EKS to auto add/reduce alarm when the node up or down, because the 'Nodename' likes ec2 dimension 'InstanceId'.

Again, I really thank for your reply, and if you can have any help for me, may be I can share my screen to show my environment with skype\zoom\teams any convenient for you.

**Comment by Erlichooo** [comment] 2022-05-15 10:52
> > @watsonjm Hello, I have seen that you use the auto-alarm lambda for Container Insight. I want know is that work. I did some job with EKS, and also use Container Insight, but I got some issue for this that alarm could not been created. If any reply I will really appreciate it.
> 
> Hi @Erlichooo Yes, I was able to create some custom alarms for EKS Container Insights. It's been a while but I can probably still help, what alarm are you trying to create, and what issues are you having?

Tks so much that your reply @watsonjm 
I have met the problem that when I set Nodename dimension for the Container Insights auto add/reduce alarm when the EKS add/reduce some nodes. The problem is the alarm of auto part could not work. And I show my node tag just like
AutoAlarm-ContainerInsights-node_memory_utilization-ClusterName-tmp-GreaterThanThreshold-1m-Average

I saw your tag with specific dimension 'Nodename', but I thought it is not suit for EKS to auto add/reduce alarm when the node up or down, because the 'Nodename' likes ec2 dimension 'InstanceId'.

Again, I really thank for your reply, and if you can have any help for me, may be I can share my screen to show my environment with skype\zoom\teams any convenient for you.
